FROM python:3.14.4-slim-bookworm AS build
WORKDIR /app
COPY app.py app.py
RUN pip install --no-cache-dir flask && pip install flask && apt update && apt install -y build-essential
        
FROM python:3.14.4-slim-bookworm 
WORKDIR /app
COPY --from=build /app .
RUN pip install flask
EXPOSE 5000
ENTRYPOINT ["python"]
CMD [ "app.py" ]

