apiVersion: v1
kind: Service
metadata:
  name:  externalname-service
spec:
  type: ExternalName
  externalName: endpointof.database.name

#This external service configuration is bit different as shown above since the service is comes out of the k8s

      
    